java_test(
    name = "app-config-test",
    srcs = glob(["*.java"]),
    test_class = "com.bmuschko.app.config.AllTests",
    deps = [
        "//src/main/java/com/bmuschko/app/config:app-lib",
        "@maven//:junit_junit"
    ]
)